alert("Error! Please enter a valid password ")
alert("Welcome to JS Land\nHappy Codeing")
alert('Welcome To JS Land')
alert("Happy Codeing\nPreventing this page additional dialog box")
console.log("this my console my name is ayaan faheem")